version: "3" 
# Defines which compose version to use
services:
  db:
    image: mysql:8
    # image: mysql:8 indicates the MySQL database container image from Docker Hub used in this installation.
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      # Previous four lines define the main variables needed for the MySQL container to work: database, database username, database user password, and the MySQL root password.
    volumes:
      - mysql:/var/lib/mysql
    # ports:
    #   - 3306:3306

  phpmyadmin:
    depends_on:
      - db
    image: bitnami/phpmyadmin
    restart: always
    ports:
      - '4011:8080'
    environment:
      DATABASE_HOST: db:3306
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      # PMA_ARBITRARY: 1

  wordpress:
    depends_on:
      - db
    build:
      context: .docker
      dockerfile: wordpress.Dockerfile
    image: kingads/wordpress:v2
    restart: always
    # Restart line controls the restart mode, meaning if the container stops running for any reason, it will restart the process immediately.
    ports:
      - "3011:80"
      # The previous line defines the port that the WordPress container will use. After successful installation, the full path will look like this: http://localhost:8000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./src/:/var/www/html
      # - ${PWD}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  mysql:
# networks:
#   wpsite: